### ISSUE TITLE
My pessimistic view about this library

### ISSUE THREAD

**Issue by moluopro** [semakers/programming_blocks#1]
I think the authors are open-sourcing the library while buttonholing it and not letting people use it.  

First, the documentation in the Readme doesn't even look like a guide on how to use the library, it's overall very confusing and doesn't have an introductory stage.  

Second, the author gives a cool official example, which should be a good learning material. However, the source code for this example uses json strings instead of key elements, so it looks like the author doesn't want us to learn it easily.  

If the author had intended to maintain the project properly, and had done a good job with the documentation and the official example, the library would have gotten a lot more attention.

**Comment by semakers** [comment]
but if there is an example in the example folder, what doubt do you have? How can I help you? Unfortunately I don't have a lot of free time to dedicate to the project and write documentation other than a better developer guide through the use of the package right now, but I hope to be able to do it in the near future.

**Comment by moluopro** [comment]
This example file contains a lot of json information, but the documentation does not contain specific details：   

<img width="228" alt="screenshot" src="https://github.com/semakers/programming_blocks/assets/55039286/0df29937-1a49-4b6d-9185-ff1d023d4b64">    

Hopefully this project will be improved, both in terms of an easy-to-use API and clearer documentation.

**Comment by semakers** [comment]
I understand, if it was my mistake not to specify, the information in json format is not part of the api or package tools, it is rather the result of the programming of an end user, and I put it there to demonstrate that a project can be loaded previously programmed by a final user, but so that you as a developer can create new blocks you do not need to nor should you modify that json, only the dart files that are in the example, if you like I can guide you better if you write to my personal email semakers@gmail.com

**Comment by moluopro** [comment]
Ok, thanks for your reply, I have understood.   
Hopefully the documentation will improve soon and this project gets more attention.
